### ISSUE TITLE
Transactions explorer v1.0.0

### ISSUE THREAD

**Issue by AeneasPM** [AeneasPlatform/AeneasElectronClient#8]
Need to add to blockchain explorer (built in client) facility to check and to view input and output transactions.

Tap Balances -> click Load Balances -> loading all non-zero balances account list.

1. Make each account clickable.
2. Goal on account click - a table-ledger - with input/output account transactions.
3. Table structure:
- **Date** (format dd/mm/yyyy + timestamp), 
- **Amount** (in ASH with 8 digits after dot) 
- **Fee** (in ASH with 8 digits after dot), 
- **Account** (column with "AEx**(full sender account)->You" if input transaction and "You->AEx**(full receiver account)" - if output transaction), 
- **Height** (including block number when included) 
- **Confirmations** (block number after including block, if more than 1440 - then just place 1440+).

**Comment by AeneasPM** [comment]
To compress table output, possible to change "AEx**(full sender account)->You" - to "Sender->You" and "You->Receiver" where to to show full sender/receiver account like a tip/popup on mouse click.

**Comment by Fly-Style** [comment]
Done in #9.
